name: Pre-Release Checks

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/project.yml'

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.repository != 'turing85/build-quarkus' }}

permissions:
  actions: write
  checks: write
  pull-requests: write

jobs:
  recreate-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Publish Report
        uses: turing85/publish-reports@2
        with:
          recreate-comment: true

  validate-version-number:
    runs-on: ubuntu-latest

    needs:
      - recreate-comment

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Release Information
        id: release-info
        uses: mikefarah/yq@v4.44.3
        with:
          cmd: yq '.release.current-version' .github/project.yml

      - name: Validate new version number
        run: |
          version="${{ steps.release-info.outputs.result }}"
          
          pattern="^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+*$"
          if ! [[ "${version}" =~ $pattern ]]
          then
            echo "version string [${version}] does not conform to pattern [0.0.0]. Aborting."
            exit 1
          fi

      - name: Update PR status comment on success
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ success() }}
        with:
          append: true
          header: reports
          message: ${{ format('<h3>🥳 <code>{0}</code> is a valid version number</h3>', steps.release-info.outputs.result) }}
          GITHUB_TOKEN: ${{ github.token }}

      - name: Update PR status comment on failure
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ failure() }}
        with:
          append: true
          header: reports
          message: ${{ format('<h3>😔 <code>{0}</code> is not a valid version number</h3>', steps.release-info.outputs.result) }}
          GITHUB_TOKEN: ${{ github.token }}